### ISSUE TITLE
Tutorial chest: sometimes gets warning "Item to buy not found"

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#130]

**Comment by ingmargoudt** [comment]
I can not reproduce this, tested several times. Error message is thrown in:

Engine/Sockethandler.js:659,

**Comment by nickjanssen** [comment]
I also did not manage to reproduce this...damnit

**Comment by bsparks** [comment]
I haven't tried, but I believe that chests restock, and if you are sitting on the chest with it open, (any chest) long enough that a restock occurs on the server, the actual items on the UI might not match. Which I was thinking to maybe do some restock checking since it doesn't _need_ to restock if the item is actually there.

**Comment by ingmargoudt** [comment]
possible solution: 

each lootable maintains a list of users that is currently accessing that lootable (i.e.: have the loot screen opened). upon restock: send an update to all users in that list

**Comment by bsparks** [comment]
this one actually should be fixed, it's not keeping a list, but it is sending an update when it's restocked. also the restock is no longer restocking items that dont need to be restocked.
