### ISSUE TITLE
IB logs me out after a while

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#146]
Any idea to make this so you basically never log out? @bsparks

**Comment by ingmargoudt** [comment]
in http/server.js:
var params = {
            log: 0,
            'close timeout': isProduction ? (60 \* 3) : 86400,
            'heartbeat timeout': isProduction ? (60 \* 3) : 86400,
            'heartbeat interval': isProduction ? (20 \* 3) : 86400,
            'polling duration': isProduction ? (25 \* 3) : 86400
        };
These values are in seconds, so on production environment it should be 3 minutes, on any other environment it should be 24 hours. The parameter to change would be 'heartbeat timeout'

**Comment by nickjanssen** [comment]
Sorry I meant the login session, not the socket values. After a while it justs asks me to log in again instead of remembering me like it was in PHP.

**Comment by ingmargoudt** [comment]
How long does it take for you to be logged out by the server? It looks like the cookie timeout is set to 1 hour

**Comment by bsparks** [comment]
the cookie timeout is here: https://github.com/ironbane/IronbaneServer/blob/master/src/server/http/server.js#L92

we could maybe set it to 24 hrs or even maybe a week, but I don't think you want forever or else it will create a security flaw. the session token is stored in the cookie now instead of the username and password, so if the cookie is compromised they _can_ login using that session, but they wont be able to create new sessions without the credentials. having the session expire prevents a hacker from having a permanent login.

**Comment by nickjanssen** [comment]
Don't you think it will be annoying having to log in everyday? What about google or facebook? They just always remember you, provided you use their service from time to time. What security issue could there be?
I vote for a month.

**Comment by bsparks** [comment]
im fine with a month, gmail makes me sign in every now and then (it might be monthly or quarterly even, I haven't tracked) even tho I am signed in every day. really, my point was just any length of time besides "forever" is good :)
