### ISSUE TITLE
get rid of bbcode, implement wysiwyg and markdown

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#153]

**Comment by ingmargoudt** [comment]
maybe its an idea to fix this together with migrating to an angularJS driven forum/website?

**Comment by bsparks** [comment]
even in the angular web version I was using bbcode. I don't think using markdown for user posts is a good plan, it opens up too many html issues I think. bbcode is much more restrictive and simpler for general users as well I think. for the angular version I was making markdown for the admin page creation, which I think makes sense because you shouldn't have to worry as much about what admin's post. why don't we like bbcode? (there may be a different solution, other than markdown)

**Comment by ingmargoudt** [comment]
Actually what I meant was that if we want changes to the forum or portal, then it could best be done while migrating to angularJS

**Comment by nickjanssen** [comment]
I think bbcode totally sucks :P having to wrap clumsy tags around text is just plain annoying (not to mention super buggy currently), better to use a (decent) wysiwyg. I also think markdown is a way better option that what we have now, considering how easy it is to make lists, headers and images. But that's maybe from a coder's perspective. It doesn't hurt to support it nevertheless, even if they are using wysiwyg.

Here is a good html5 wysiwyg editor I used in the past, free and open source: http://xing.github.io/wysihtml5/

**Comment by bsparks** [comment]
well, we can certainly switch, here is the current editor: http://markitup.jaysalvat.com/examples/bbcode/ that was being used in the webapi branch, it supports bbcode and markdown but it's not a wysiwyg i'll check out that one you posted.
