### ISSUE TITLE
/join

### ISSUE THREAD

**Issue by lschans** [ironbane/IronbaneServerLegacy#264]
You can /join a room with the same name a character has.

So /join nikke works

**Comment by bsparks** [comment]
on dev? I just fixed that. note: if you are an editor account you can do this, you aren't restricted from joining any channel. this is so that moderators can moderate even PM channels (to validate claims that someone is harassing them for instance). otherwise if you sign in as a guest, you shouldn't be able to.

unless you are also talking about when Nikke is not logged on. This is also possible, as I don't check the character database each time for all the combinations, however, when Nikke logs on (or any other character) then it does go through and kick anyone who was trying to squat in their channel out.
