### ISSUE TITLE
Items showing their attack speed under the damage

### ISSUE THREAD

**Issue by TheRestIsATest** [ironbane/IronbaneServerLegacy#268]
IMO this has to be added quickly.

**Comment by nickjanssen** [comment]
+1

**Comment by ingmargoudt** [comment]
quite an easy fix, can we remove the itemID or shall we keep it for
debugging purposes? I have never used it though...you can easily query the
players inventory in the database for that

2013/10/30 Nick Janssen notifications@github.com

**Comment by nickjanssen** [comment]
@ingmargoudt not sure what you mean? Remove it where and why?

We need a sprite to put next to the attack speed stat @Meanapple

**Comment by ingmargoudt** [comment]
iirc when you hover over an item, the itemID is also shown in the pop up

2013/10/30 Nick Janssen notifications@github.com

**Comment by nickjanssen** [comment]
It only shows on dev:
https://github.com/ironbane/IronbaneServer/blob/master/src/client/game/js/Game/Hud.js#L624

**Comment by TheRestIsATest** [comment]
[img]http://i.imgur.com/Fpqu6Bx.png[/img]

**Comment by ingmargoudt** [comment]
added in 3b508aa

**Comment by bsparks** [comment]
like the icon, not sure how it fits, currently Damage is in text, with hearts for how much

since speed is like 1.2 seconds how do we display the icon? could be half icon increments rounding up, but wouldn't be very accurate (half second increments). otherwise instead of the words "Damage" and "Attackspeed" we could just show icons, we'd then need a "Damage" icon.

another alternative would be to be much more vague and boil certain ranges down to "Slow", "Fast", "Fastest" or something like that (possibly different icons depicting that?)

**Comment by ingmargoudt** [comment]
Attackspeed is added. Let's discuss (design) issues coming from this in a new issue
