### ISSUE TITLE
[Feature] Banking

### ISSUE THREAD

**Issue by bsparks** [ironbane/IronbaneServerLegacy#37]
Create bank units; Prolly they should have AI but not necessarily be a creature, could also be just a chest. Or both (will need to look into that code wise).

Should basically be the same as a Lootable, chest or whatnot that has 10 slots, but they are private to each user. (new DB table I think)

The banks should not be global, they should be per chest/character so that you can have different banks in different towns or hidden chests somewhere with different items.

**Comment by ghost** [comment]
There are many users that wanted banks to store items across accounts, and not just per character. Otherwise banks have no purpose other than to serve as an extended inventory since in death they'd all be lost anyway. So IMO chests should be per user.

With that said, I think it'd be neat to require players to pay money for each slot (at an increasing rate). This prevents empty slots, since players will only want to spend money if they really need the space, and provides yet another incentive for gold, since at the moment there are few uses for it.

The ten slot limit also encourages users to bank across towns rather than focus everything in one area, so I thumbs-up that. Being shared between characters under one account also increases the importance of banks, since they'd need to be more well-managed if a player has the max number of slots taken up.

Finally, to expand on your "hidden chests somewhere with different items" that got me thinking that, perhaps here and there can be little 1-slot areas like "under a rock" or "in a tree" where players can place items in strategic little hide-aways. There's more to it, of course, but it's a start. :)
