### ISSUE TITLE
upgrade THREE

### ISSUE THREAD

**Issue by bsparks** [ironbane/IronbaneServerLegacy#38]
upgrade THREE.js to r58 and also update the octree, then test it.

have to clear up a number of deprecated calls

**Comment by ingmargoudt** [comment]
I think we can postpone this to a future 0.5 release. This issue is not blocking for the upcoming 0.3

**Comment by nickjanssen** [comment]
Working on a branch locally for this. Need to upgrade to r60 in order to implement all the latest hot stuff like Blender-style editing and PointerLock controls.

# r59 → r60
- [x] `Face4` is removed. Use 2 `Face3` to emulate it.

# r58 → r59
- [x] `Object3D.rotation` is now of type `THREE.Euler`.
- [x] Removed `Object3D.useQuaternion`. The library now uses quaternions by default. However, there is some magic in place to keep `Object3D`'s `rotation` (`Euler`) working.
- [x] Moved `Object3D.eulerOrder` to `Object3D.rotation.order`.
- [x] Moved `Object3D.defaultEulerOrder` to `Euler.DefaultOrder`.
- [x] Removed `setGeometry()` and `setMaterial()` from `Mesh`.
- [x] Removed `Vector3.setEulerFromQuaternion()`, use `Euler.setFromQuaternion()` instead.

# r57 → r58
- [x] Removed `Matrix4`'s `translate()`, `rotateX()`, `rotateY()`, `rotateZ()`, `rotateByAxis()` and `crossVector()`.
- [x] Removed `setClearColorHex()` from `CanvasRenderer` and `WebGLRenderer`. Use `setClearColor()` instead.
- [x] Renamed `Matrix4`'s `extractPosition()` to `copyPosition()`.
- [x] Renamed `Matrix4`'s `setRotationFrom*()` to `makeRotationFrom*()`.
- [x] Renamed `Matrix4`'s `compose()` to `makeFromPositionQuaternionScale()`.
- [x] Renamed `Object3D`'s `getChildByName()` to `getObjectByName()`.
- [x] Removed `Object3D`'s `matrixRotationWorld` property.

# r56 → r57
- [x] For `BufferGeometry`
- [x] `geometry.verticesNeedUpdate` to `geometry.attributes.position.needsUpdate`
- [x] `geometry.elementsNeedUpdate` to `geometry.attributes.index.needsUpdate`
- [x] `geometry.normalsNeedUpdate` to `geometry.attributes.normal.needsUpdate`
- [x] `geometry.uvsNeedUpdate` to `geometry.attributes.uv.needsUpdate`
- [x] `geometry.colorsNeedUpdate` to `geometry.attributes.color.needsUpdate`
- [x] `geometry.tangentsNeedUpdate` to `geometry.attributes.tangent.needsUpdate`
- [x] `*` -> `geometry.attributes.custom.needsUpdate`
- [x] Removed `Matrix4`'s `rotateAxis`. Use `Vector3.transformDirection( matrix )` instead.
- [x] Removed `AsteriskGeometry`.
- [x] Removed `Color`'s `setHSV`. Use `ColorConverter.setHSV( color, h, s, v )` instead.
- [x] Renamed `JSONLoader`'s `createModel()` to `parse()`.

# r55 → r56
- [x] Removed `getPosition()` and `getColumn*()` from `Matrix4`
- [x] `Color.setHSV()` and `Color.getHSV()` replaced by `.setHSL()` and `.getHSL()`
- [x] Replaced `ColorUtils.adjustHSV()` with Color's `.offsetHSL()`
- [x] Renamed `Box3/Line3/Plane/Ray/Sphere`'s `.transform()` to `applyMatrix4()`

# r54 → r55
- [x] `Matrix3.multiplyVector3()` changed to `Vector3.applyMatrix3()`
- [x] `Matrix4.multiplyVector3()` changed to `Vector3.applyMatrix4()` and `Vector3.applyProjection()`
- [x] `Matrix4.multiplyVector4()` changed to `Vector4.applyMatrix4()`
- [x] `Quaternion.multiplyVector3()` changed to `Vector3.applyQuaternion()`
- [x] Renamed `Color` methods:
- [x] `.lerpSelf()` to `.lerp()`
- [x] Renamed `Vector2`, `Vector3` and `Vector4` methods:
- [x] `.add()` to `.addVectors()`
- [x] `.addSelf()` to `.add()`
- [x] `.sub()` to `.subVectors()`
- [x] `.subSelf()` to `.sub()`
- [x] `.minSelf()` to `.min()`
- [x] `.maxSelf()` to `.max()`
- [x] `.clampSelf()` to `.clamp()`
- [x] `.lerpSelf()` to `.lerp()`
- [x] Renamed `Matrix4` methods:
- [x] `.multiply()` to `.multiplyMatrices()`
- [x] `.multiplySelf()` to `.multiply()`
- [x] Renamed `Quaternion` methods:
- [x] `.multiply()` to `.multiplyQuaternions()`
- [x] `.multiplySelf()` to `.multiply()`
- [x] Renamed `Frustum` methods:
- [x] `.contains()` to `.intersectsObject()`
- [x] Moved `GeometryUtils.explode` to `ExplodeModifier`
- [x] Moved `GeometryUtils.tessellate` to `TessellateModifier`
- [x] Moved `ShaderUtils.lib` to `ShaderLib`
- [x] `Matrix4.makeTranslation` and `Matrix4.makeScale` now take  three scalars instead of `Vector3`.

# r53 → r54
- [x] `Sprite` material properties are now in `SpriteMaterial`, used like this `new THREE.Sprite( new THREE.SpriteMaterial( { color: 0xff0000, map: texture, alphaTest: 0.5 } ) )`.
- [x] Renamed migrated sprite material properies: `Sprite.affectedByDistance` => `SpriteMaterial.sizeAttenuation` and `Sprite.mergeWith3D` => `SpriteMaterial.depthTest`
- [x] Renamed `renderer.shadowMapCullFrontFaces` => `renderer.shadowMapCullFace` (default value `true` => `THREE.CullFaceFront`, other option `false` => `THREE.CullFaceBack`).
- [x] Renamed `color.getContextStyle` to `color.getStyle`.
- [x] Moved `Ray` casting methods to `Raycaster`.
- [x] `Rectangle` replaced  with `Box2`.
- [x] `UV` replaced with `Vector2`. This means `.u` and `.v` are now `.x` and `.y`.
- [x] `Matrix4.makeTranslation` and `Matrix4.makeScale` now take `Vector3` instead of three scalars.
- [x] Moved `SubdivisionModifier` out of the build to `examples/js/modifiers`.
- [x] Renamed and moved `Renderer.deallocateObject()` => `Geometry.dispose()` and `BufferGeometry.dispose()`.
- [x] Renamed and moved `Renderer.deallocateRenderTarget()` => `WebGLRenderTarget.dispose()`.

# r52 → r53
- [x] `Sprite` now doesn't get anymore size automatically from the image size, use `sprite.scale.set( imageWidth, imageHeight, 1.0 )` to achieve the old behavior
- [x] `SceneLoader`and scene format now use `widthSegments`, `heightSegments`, `depthSegments` instead of `segmentsWidth`, `segmentsHeight`, `segmentsDepth` for definitions of plane, cube and sphere geometries
- [x] `SceneLoader`and scene format now use `material` property with single material id string instead of `materials` array for meshes
- [x] `MeshPhongMaterial` now uses `perPixel = true` by default
- [x] `WebGLRenderer` constructor doesn't use anymore `maxLights` parameter: shaders will be generated with the exact number of lights in the scene (it's now up to the application layer to make sure shaders compile on a particular system)
- [x] `ColorUtils.rgbToHsv()` got moved into `Color.getHSV()`
- [x] `Geometry` no longer has a `materials` property. `MeshFaceMaterials` usage is now like this: `new THREE.Mesh( geometry, new THREE.MeshFaceMaterials( [ material1, material2 ] ) )`. Meaning that `face.materialIndex` will map the array passed to `MeshFaceMaterials`.
- [x] Loader callbacks which previously only had `geometry` parameter, are now also passed a second one: `materials`: `loader.load( 'file.js', function ( geometry, materials ) {} )`.
- [x] `GeometryUtils.clone()` is now a method in `Geometry`.
