### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#6]
Hey Ben,

I have the feeling that you'd like to rewrite the whole server from scratch? While indeed a lot of code is badly written, could we rather slowly refactor everything instead commenting out the old code now? We just had a spike in traffic and the server needs a lot of maintenance, and would like to commit those changes to the new server we're working on. Can't we just turn the existing code into cleaner code, with proper `module.exports`?

So my request is, can we uncomment the old code again and make it work with what we got (so that we can still use the old server code currently with the old client) and we can work our way from there.

**Comment by bsparks** [comment]
Well, I'm perfectly fine with getting it up and running asap. I'm not sure how easy that will be tho, I've already made some changes to the database for example. Also I never really got things working well using PHP so it's difficult for me to test.

I did however plan to re-use as much code as possible and just move it to modules. I think the problem is that everything was so intertwined between PHP and Node, even in the server, that I find it hard to tell where a request is and what its response should be.

So I guess my answer is, I'd love to do that but I'm not sure how. I did try to set it up so that we could turn the http portion off if we wanted to (though I haven't fully tested that theory). Perhaps I can shift my focus more towards the game server portion than the website for now.

**Comment by nickjanssen** [comment]
Sorry I think I explained badly. I meant the game server, not http. The idea would be that we can continue work just like now, so we can have an AngularJS version soon, but the game server should still be able to communicate with the old PHP client if that makes sense. So, the only thing that should still work on the new game server are the socket connections (on connect, disconnect, etc) so that when I run the old game.php on the production server, it can still connect as if nothing changed. On ironbane.com, currently runs the old server from the master branch. I would then shut it down, switch to the webapi branch and start the server. This will then indeed have the new node http server enabled, but we won't use that in production until the new angular website is ready. For now then it can then run parallel with the old PHP code, for compatibility.

I know that the PHP version doesn't work for you now, and there is also no need for that. We can just continue working on the Angular website until it finally works for you guys as well.

**Comment by bsparks** [comment]
I realize it's the game server, but I guess I'm not sure what would be gained by this.. maybe if I knew more of what you wanted to update. Maybe it would be easier to just apply those updates into the main branch and then we can incorporate the changes into the new server style.

on another note, I'm going to attempt to attend the Skype conference tomorrow if discussing there will help

edit: oic so it's in the nicktest branch? hmmmm

**Comment by bsparks** [comment]
I think we are basically doing this now :+1:
